version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12.x
      docker: 18
    commands:
      - npm i
      - curl -o jq https://stedolan.github.io/jq/download/linux64/jq
      - chmod +x ./jq
  build:
    commands:
      - echo Build started on `date`
      - docker-compose up -d
      - echo Curl to mysql
      - curl -v telnet://127.0.0.1:3306
      - echo Build completed on `date`
