version: "3"

services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_USER=root
      - MYSQL_DATABASE=db
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/mysql:/docker-entrypoint-initdb.d
volumes:
  db-data:
